#!/bin/env bash
WEBURL="https://files.minecraftforge.net/net/minecraftforge/forge/"

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息...${background}
until ForgeVersion=$(curl ${WEBURL} | grep 'href="index_' | sed "s|<a href=\"index_.*.html\">||g" | sed "s|</a>||g")
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

for version in ${ForgeVersion}
do
  options="${options} ${version} Forge"
done

ScreenSizeMenu
ForgeCoreVersion=$(dialog \
--title "MCServer" \
--menu "您希望适配哪个Minecraft版本?" \
${HEIGHT} ${WIDTH} ${OPTION} ${options} \
3>&1 1>&2 2>&3)

echo ${ForgeCoreVersion} > version

adfoc='https://adfoc.us/serve/sitelinks/?id=271228&url='
echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}下载链接...${background}
until ForgeURL=$(curl ${WEBURL}index_${ForgeCoreVersion}.html | \
                grep Installer | \
                head -n 1 | \
                grep -oP 'href=\K[^ ]+' | \
                sed 's|"||g' | sed "s|${adfoc}||g")
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

Download Forge.jar ${ForgeURL}

echo -e ${blue}[${green}*${blue}] ${cyan}正在构建服务端...${background}
until java -server -Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN -jar Forge.jar --installServer
do
  echo -e ${blue}[${red}*${blue}] ${cyan}构建失败 ${yellow}三秒后重试${background}
  sleep 3s
done



