#!/bin/env bash
AFHOME=$1
source $AFHOME/Manage/config

WEBURL="https://meta.fabricmc.net"

if $(whiptail --title "MCServer-BDS" \
--yes-button "稳定版" \
--no-button "测试版" \
--yesno "请选择您的版本" \
${HEIGHT} ${WIDTH} \
3>&1 1>&2 2>&3)
then
    boolean=true
else
    boolean=false
fi

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息...${background}
until GameVersion=$(curl ${WEBURL}/v2/versions/game)
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

Num=$(expr $(echo ${GameVersion} | jq '. | length') - 1)
for ((i=0; i<=${Num}; i++))
do
  stable=$(echo ${GameVersion} | jq .[${i}].stable)
  echo -en "\r 已处理${i}"
  if [[ "${stable}" == "true" ]]
  then
    FabricVersionRelease="${FabricVersionRelease} $(echo ${GameVersion} | jq .[${i}].version)"
  elif [[ "${stable}" == "false" ]]
  then
    FabricVersionBeta="${FabricVersionBeta} $(echo ${GameVersion} | jq .[${i}].version)"
  fi
done

for version in $(echo ${FabricVersionRelease} | sed 's/"//g')
do
  options="${options} ${version} Fabric"
done

ScreenSizeMenu
FabricCoreVersion=$(whiptail \
--title "MCServer" \
--menu "您希望适配哪个Minecraft版本?" \
${HEIGHT} ${WIDTH} ${OPTION} ${options} \
3>&1 1>&2 2>&3)

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}loader 版本信息${background}
until LoaderVersion=$(curl ${WEBURL}/v2/versions/loader | jq .[0].version | sed 's/"//g')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}installer 版本信息${background}
until InstallerVersion=$(curl ${WEBURL}/v2/versions/installer | jq .[0].version | sed 's/"//g')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

FabricDownloadURL="https://meta.fabricmc.net/v2/versions/loader/${FabricCoreVersion}/${LoaderVersion}/${InstallerVersion}/server/jar"

Download Fabric.jar ${FabricDownloadURL}