#!/bin/env bash
WEBURL="https://mcversions.net/"

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息...${background}
until JavaVersion=$(curl ${WEBURL} | grep -oP 'data-version=\K[^ ]+' | sed 's/"//g')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

for version in ${JavaVersion}
do
  options="${options} ${version} Java"
done

ScreenSizeMenu
JavaCoreVersion=$(dialog \
--title "MCServer" \
--menu "您希望适配哪个Minecraft版本?" \
${HEIGHT} ${WIDTH} ${OPTION} ${options} \
3>&1 1>&2 2>&3)

echo ${JavaCoreVersion} > version

McversionsURL="https://mcversions.net/download/${JavaCoreVersion}"

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}下载链接...${background}
until JavaServerURL=$(curl ${McversionsURL} | grep -oP 'href=\K[^ ]+' | sed 's/"//g' | grep 'server.jar')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

Download Server.jar ${JavaServerURL}
