#!/bin/env bash
WEBURL="https://mcversions.net/"

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息...${background}
until JavaVersion=$(curl ${WEBURL} | grep -oP 'data-version=\K[^ ]+' | sed 's/"//g')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

StableReleases=$(echo $JavaVersion | awk -F' 1.0 ' '{print $1}' && echo 1.0)

SnapshotPreview=$(echo $JavaVersion | sed s/"$(echo ${StableReleases}) "//g | awk -F' 1.3 ' '{print $1}' && echo 1.3)

ScreenSizeMsgbox
if $(whiptail --title "MCServer-BDS" \
--yes-button "稳定版" \
--no-button "测试版" \
--yesno "请选择您的版本" \
${HEIGHT} ${WIDTH} \
3>&1 1>&2 2>&3)
then
  JavaVersion="${StableReleases}"
else
  JavaVersion="${SnapshotPreview}"
fi

for version in ${JavaVersion}
do
  options="${options} ${version} Java"
done

ScreenSizeMenu
JavaCoreVersionType=$(whiptail \
--title "MCServer" \
--menu "您希望适配哪个Minecraft版本?" \
${HEIGHT} ${WIDTH} ${OPTION} ${options} \
3>&1 1>&2 2>&3)

ScreenSizeMenu
JavaCoreVersion=$(whiptail \
--title "MCServer" \
--menu "您希望适配哪个Minecraft版本?" \
${HEIGHT} ${WIDTH} ${OPTION} ${options} \
3>&1 1>&2 2>&3)

echo ${JavaCoreVersion} > version

McversionsURL="https://mcversions.net/download/${JavaCoreVersion}"

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}下载链接...${background}
until JavaServerURL=$(curl ${McversionsURL} | grep -oP 'href=\K[^ ]+' | sed 's/"//g' | grep 'server.jar')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

Download Server.jar ${JavaServerURL}
