#!/bin/env bash
WEBURL="https://getbukkit.org/download/spigot"

until SpigotVersion=$(curl ${WEBURL} | grep '<h2>' | sed 's|<h2>||g' | sed 's|</h2>||g')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

for version in ${SpigotVersion}
do
  options="${options} ${version} Spigot"
done

ScreenSizeMenu
SpigotCoreVersion=$(dialog \
--title "MCServer" \
--menu "您希望适配哪个Minecraft版本?" \
${HEIGHT} ${WIDTH} ${OPTION} ${options} \
3>&1 1>&2 2>&3)

echo ${ServerCoreVersion} > version
SpigotDownloadURL="https://download.getbukkit.org/spigot/spigot-${SpigotCoreVersion}.jar"

wgetDownload Spigot.jar ${SpigotDownloadURL}