#!/bin/env bash
# Frpc Version 0.57.0
AFHOME=$1
source $AFHOME/Manage/config

ServerName=FRPC
config=$AFHOME/Manage/config
StartSoftware=$(grep StartSoftware ${config} | sed 's/StartSoftware=//g')
StartSoftwarePath=$AFHOME/Manage/StartSoftware
ConfigPath=$AFHOME/Manage/FRPC/frpc.toml

StartCheck(){
if ps all | sed '/grep/d' | grep frpc.toml > /dev/null 2>&1
then
  return 0
else
  return 1
fi
}

ConfigCheck(){
if [ -e /sd/Download/frpc.toml ]
then
  ConfigPath="/sd/Download/frpc.toml"
  return 0
elif [ -e /sdcard/Download/frpc.toml ]
then
  ConfigPath="/sdcard/Download/frpc.toml"
  return 0
elif [ -e /storage/emulated/0/Download/frpc.toml ]
then
  ConfigPath="/storage/emulated/0/Download/frpc.toml"
  return 0
elif [ -e $AFMCSS/frpc.toml ]
then
  ConfigPath="$AFMCSS/frpc.toml"
  return 0
else
  return 1
fi
}

ARCH=$(uname -m)
case "$ARCH" in
  aarch64|arm64|armv8|armv9)
    ARCH="Arm64"
    ;;
  x86_64|x64|amd64)
    ARCH="Amd64"
    ;;
  *)
    ScreenSizeMsgbox
    dialog --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n无法运行WebDAV" \
    ${HEIGHT} ${WIDTH}
    exit 3
    ;;
esac

FRPCMENU(){
ScreenSizeMenu
Number=$(whiptail \
--title "FRPC-SM" \
--menu "FRPC管理" \
${HEIGHT} ${WIDTH} ${OPTION} \
"1" "🍀 启动FRPC" \
"2" "🌵 日志FRPC" \
"3" "🌸 关闭FRPC" \
"4" "🍁 配置FRPC" \
"0" "🍥 返回主菜单" \
3>&1 1>&2 2>&3)
feedback=$?
if [ ${feedback} == 1 ]
then
  exit
fi
case ${Number} in
1)
  if grep -q test ${ConfigPath}
  then
    if ConfigCheck
    then
      cp -f ${ConfigPath} $AFMCSS/Manage/FRPC/frpc.toml
    else
      echo -e ${blue}[${yellow}*${blue}] ${cyan}FRPC无配置${background}
      echo -e ${blue}[${yellow}*${blue}] ${cyan}请将 ${yellow}frpc.toml ${cyan}放置于正确位置${background}
      echo -e ${blue}[${yellow}*${blue}] ${cyan}Termux\(手机\) ${yellow}Download/frpc.toml${background}
      echo -e ${blue}[${yellow}*${blue}] ${cyan}服务器\(电脑\)${yellow}$AFMCSS/frpc.toml${background}
      echo -en ${blue}[${green}*${blue}] ${cyan}回车返回${background};read
    return
    fi
  else
    Command="$AFMCSS/Manage/FRPC/Frpc$ARCH -c $AFMCSS/Manage/FRPC/frpc.toml"
    bash ${StartSoftwarePath} ${StartSoftware} start ${ServerName} "${Command}"
    ScreenSizeMsgbox
    if $(whiptail --title "FRPC-SM" \
    --yes-button "打开" \
    --no-button "返回" \
    --yesno "FRPC 内网穿透服务器 [已启动]\n是否打开日志?" \
    ${HEIGHT} ${WIDTH})
    then
      bash ${StartSoftwarePath} ${StartSoftware} log ${ServerName} > /dev/null 2>&1
    fi
  fi
2)
  bash ${StartSoftwarePath} ${StartSoftware} log ${ServerName} > /dev/null 2>&1
  ;;
3)
  if StartCheck
  then
    bash ${StartSoftwarePath} ${StartSoftware} stop ${ServerName} > /dev/null 2>&1
  else
    ScreenSizeMsgbox
    whiptail --title "FRPC-SM" \
    --msgbox "${ServerName} [未启动]" \
    ${HEIGHT} ${WIDTH}
  fi
  ;;
4)
  ScreenSizeMsgbox
  if ! Path=$(whiptail \
  --title "FRPC-SM" \
  --inputbox "请输入配置文件路径"\ 
  ${HEIGHT} ${WIDTH}
  3>&1 1>&2 2>&3)
  then
    return
  fi
  if [ -z ${Path} ]
  then
    ScreenSizeMsgbox
    whiptail --title "FRPC-SM" \
    --msgbox "您没有输入内容" \
    ${HEIGHT} ${WIDTH}
    return
  fi
  if cat ${Path} > /dev/null 2>&1
  then
    cat ${Path} > $AFMCSS/Manage/FRPC/frpc.toml
  else
    whiptail --title "FRPC-SM" \
    --msgbox "错误 文件不存在" \
    ${HEIGHT} ${WIDTH}
  fi
  ;;
0)
  exit
  ;;
esac
}

function LoopFRPCMENU(){
while true
do
  WebDAVMENU
  feedback=$?
  if [ ${feedback} == 3 ]
  then
    exit
  fi
  LoopFRPCMENU
done
}
LoopFRPCMENU