#!/bin/env bash
AFHOME=$1
source $AFHOME/Manage/config
InstallMinecraftBDS(){
WEBURL="https://minecraft.wiki/w/Bedrock_Dedicated_Server"
GREPURL="https://minecraft.azureedge.net/bin-linux-preview/bedrock-server-"
UpdatedVersion="Server software updated for"
BetaVersion="Server software (beta) updated for"

ScreenSizeMsgbox
if $(whiptail --title "MCServer-BDS" \
--yes-button "稳定版" \
--no-button "测试版" \
--yesno "请选择您的版本" \
${HEIGHT} ${WIDTH} \
3>&1 1>&2 2>&3)
then
    GREPURL=${UpdatedVersion}
else
    GREPURL=${BetaVersion}
fi
echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息${background}
until BDSVersion=$(curl ${WEBURL} \
                    | grep "${GREPURL}" \
                    | grep -oP '<pre class="history-json noexcerpt navigation-not-searchable">\K.*?(?=</pre>)' \
                    | awk '{print $4}' \
                    | sed 's/,//g' \
                    | sed 's/"//g')
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done

for version in ${BDSVersion}
do
  options="${version} BDS ${options}"
done

MinecraftBDSVersion=$(whiptail --title "白狐" \
--menu "请选择BDS服务器适配的MC版本" \
28 45 20 ${options} \
3>&1 1>&2 2>&3)
echo ${MinecraftBDSVersion} > version
if [[ ${GREPURL} == *"beta"* ]]
then
  BedrockDedicatedServerURL="https://minecraft.azureedge.net/bin-linux-preview/bedrock-server-${MinecraftBDSVersion}.zip"
else
  BedrockDedicatedServerURL="https://minecraft.azureedge.net/bin-linux/bedrock-server-${MinecraftBDSVersion}.zip"
fi

Download MinecraftBDS.zip ${BedrockDedicatedServerURL}

echo -e ${blue}[${green}*${blue}] ${cyan}正在解压 ${yellow}MinecraftBDS.zip${background}
unzip -oq MinecraftBDS.zip
echo -e ${blue}[${green}*${blue}] ${cyan}解压完成${background}
rm -rf MinecraftBDS.zip
}

InstallBox64(){
if [ $(command -v apt) ];then
    apt install -y build-essential cmake python3
elif [ $(command -v yum) ];then
    yum install -y epel-release
    yum install -y "Development Tools" cmake
    yum install -y python3
elif [ $(command -v dnf) ];then
    dnf install -y epel-release
    dnf install -y "Development Tools" cmake python3
elif [ $(command -v pacman) ];then
    pacman -S --noconfirm --needed base-devel cmake python38
else
    whiptail --title "白狐-Script" \
    --msgbox "十分抱歉 您的Linux具有未知的包管理器 \n无法安装编译Box64的依赖" \
    ${HEIGHT} ${WIDTH}
    exit 3
fi
URL="https://ipinfo.io"
Address=$(curl -sL ${URL} | sed -n 's/.*"country": "\(.*\)",.*/\1/p')
if [ "${Address}" = "CN" ]
then
  # 免费提供 请勿滥用
  GitMirror="https://ghproxy.arcticfox.top/https://github.com"
else
  GitMirror="https://github.com"
fi
GitBox64(){
echo -e ${blue}[${green}*${blue}] 正在克隆 ${yellow} Box64仓库${background}
if git clone --depth=1 -b main ${GitMirror}/ptitSeb/box64 ./Box64
then
  echo -e ${blue}[${green}*${blue}] ${cyan}克隆完成.${background}
else
  echo -e ${blue}[${red}*${blue}] ${cyan}克隆失败.${background}
  echo -e ${blue}[${green}*${blue}] ${cyan}切换为官方源 重试中.${background}
  GitMirror="https://github.com"
  GitBox64
fi
}
# 此段为适配termux无possible文件
if [ -d /sd ] || [ -d /sdcard ];then
  if [ ! -e /sys/devices/system/cpu/possible ];then
    mkdir -p /sys/devices/system/cpu
    if nproc
    then
      CoreNumber=$(nproc)
    else
      CoreNumber=8
    fi
    PossibleNumber="0-$(expr ${CoreNumber} - 1 )"
    echo ${PossibleNumber} > /sys/devices/system/cpu/possible
  fi
fi
GitBox64
cd Box64
mkdir build
cd build
cmake .. -D ARM_DYNAREC=ON -D CMAKE_BUILD_TYPE=RelWithDebInfo
echo -e ${blue}[${green}*${blue}] ${cyan}开始编译 ${yellow}Box64${background}
if nproc
then
  CoreNumber=$(nproc)
fi
make -j${CoreNumber}
echo -e ${blue}[${green}*${blue}] ${cyan}开始安装 ${yellow}Box64${background}
make install
mv box64 /usr/local/bin/box64
cd ../../
echo -e ${blue}[${green}*${blue}] ${cyan}安装完成${background}
rm -rf box64
}


ARCH=$(uname -m)
case "$ARCH" in
  aarch64|arm64|armv8|armv9)
    ScreenSizeMsgbox
    if [ ! $(command -v box64) ];then
      if $(whiptail --title "MCServer-BOX64" \
      --yes-button "确认" \
      --no-button "返回" \
      --yesno "您的架构为${ARCH} \n是否安装BOX64来运行MinecraftBDS服务器?" \
      ${HEIGHT} ${WIDTH} \
      3>&1 1>&2 2>&3)
      then
        InstallBox64
      else
        exit 3
      fi
    fi
    InstallMinecraftBDS
    ;;
  arm*|aarch32)
    ScreenSizeMsgbox
    whiptail --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n无法运行MinecraftBDS" \
    ${HEIGHT} ${WIDTH}
    exit 3
    ;;
  x86_64|x64|amd64)
    InstallMinecraftBDS
    ;;
  i386|i686|x86)  
    ScreenSizeMsgbox
    whiptail --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n无法运行MinecraftBDS" \
    ${HEIGHT} ${WIDTH}
    
    exit 3
    ;;
  *)
    ScreenSizeMsgbox
    whiptail --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n属于未知架构" \
    ${HEIGHT} ${WIDTH}
    exit 3
    ;;
esac