#!/bin/env bash
APIURL="https://api.papermc.io/v2/projects/paper"

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息...${background}
until PaperVersion=$(curl https://api.papermc.io/v2/projects/paper | jq .versions)
do
  echo -e ${blue}[${red}*${blue}] ${cyan}获取失败 ${yellow}三秒后重试${background}
  sleep 3s
done
echo -e ${blue}[${green}*${blue}] ${cyan}正在处理 ${yellow}版本信息...${background}
Num=$(expr $(echo ${PaperVersion} | jq '. | length') - 1)
for ((i=0; i<=${Num}; i++))
do
  for version in $(echo ${PaperVersion} | jq .[${i}] | sed 's/"//g')
  do
    options="${version} Paper ${options}"
  done
done
i=

ScreenSizeMenu
PaperCoreVersion=$(whiptail \
--title "MCServer" \
--menu "您希望适配哪个Minecraft版本?" \
${HEIGHT} ${WIDTH} ${OPTION} ${options} \
3>&1 1>&2 2>&3)

echo ${PaperCoreVersion} > version

PaperURL="https://api.papermc.io/v2/projects/paper/versions/${PaperCoreVersion}"
curl https://api.papermc.io/v2/projects/paper/versions/1.20.4 | jq .builds

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}构建编号...${background}
BuildsJson=$(curl ${PaperURL})
Number=$(expr $(echo ${BuildsJson} | jq '.builds | length') - 1)
BuildsVersion=$(echo ${BuildsJson} | jq .builds[${Number}])

echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}下载链接...${background}
JsonRead=downloads.application.name
PaperFileName=$(curl ${PaperURL}/builds/${BuildsVersion} | jq .${JsonRead} | sed 's/"//g')
PaperDownloadURL=${PaperURL}/builds/${BuildsVersion}/downloads/${PaperFileName}

Download Paper.jar ${PaperDownloadURL}

