#!/bin/env bash
AFHOME=$1
source $AFHOME/Manage/config

ServerName=WebDAV
config=$AFHOME/Manage/config
StartSoftware=$(grep StartSoftware ${config} | sed 's/StartSoftware=//g')
StartSoftwarePath=$AFHOME/Manage/StartSoftware
ConfigPath=$AFHOME/Manage/WebDAV/config.yaml

StartCheck(){
Port=$(grep port ${ConfigPath} | awk '{print $2}')
ScreenSizeMsgbox
if bash ${StartSoftwarePath} ${StartSoftware} list 2>&1 | grep -q ${ServerName} > /dev/null 2>&1
then
  if ncat -z -w 1 127.0.0.1 ${Port}
  then
    return 0
  else
    whiptail --title "WebDAV-SM" \
    --msgbox "终端名: ${StartSoftware} [被占用]" \
    ${HEIGHT} ${WIDTH}
    return 1
  fi
elif ncat -z -w 1 127.0.0.1 ${Port}
then
  if bash ${StartSoftwarePath} ${StartSoftware} list 2>&1 | grep -q ${ServerName} > /dev/null 2>&1
  then
    return 0
  else
    whiptail --title "WebDAV-SM" \
    --msgbox "端口: ${Port} [被占用]" \
    ${HEIGHT} ${WIDTH}
    return 1
  fi
else
  return 2
fi
}

WaitingProgressBar(){
  i=0
  ScreenSizeMsgbox
  Port=$(grep port ${ConfigPath} | awk '{print $2}')
  i=0
  {
    until ncat -zw 0.1 127.0.0.1 ${Port} &> /dev/null
    do
      echo ${i}
      ((i++))
      sleep 0.4s
    done
  } | whiptail --title "WebDAV-SM" --gauge "WebDAV正在启动" ${HEIGHT} ${WIDTH} 0
}

ARCH=$(uname -m)
case "$ARCH" in
  aarch64|arm64|armv8|armv9)
    ARCH="arm64"
    ;;
  x86_64|x64|amd64)
    ARCH="amd64"
    ;;
  *)
    ScreenSizeMsgbox
    dialog --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n无法运行WebDAV" \
    ${HEIGHT} ${WIDTH}
    exit 3
    ;;
esac

WebDAVMENU(){
ScreenSizeMenu
Number=$(whiptail \
--title "WebDAV-SM" \
--menu "WebDAV管理" \
${HEIGHT} ${WIDTH} ${OPTION} \
"1" "🍀 启动WebDAV" \
"2" "🌸 关闭WebDAV" \
"3" "🍁 配置WebDAV" \
"0" "🍥 返回主菜单" \
3>&1 1>&2 2>&3)
feedback=$?
if [ ${feedback} == 1 ]
then
  exit
fi
case ${Number} in
1)
  if grep -q admin ${ConfigPath}
  then
    ScreenSizeMsgbox
    username=$(whiptail \
    --title "WebDAV-SM" \
    --inputbox "请设置用户名" \
    ${HEIGHT} ${WIDTH} \
    3>&1 1>&2 2>&3)
    password=$(whiptail \
    --title "WebDAV-SM" \
    --passwordbox "请设置密码" \
    ${HEIGHT} ${WIDTH} \
    3>&1 1>&2 2>&3)
    sed -i "s/ - username: admin/  - username: ${username}/g" ${ConfigPath}
    sed -i "s/   password: admin/    password: ${password}/g" ${ConfigPath}
    sed -i "s|   scope:*|    scope: $AFHOME|g" ${ConfigPath}
  fi
  Command="cd $AFHOME/Manage/WebDAV && ./webdav-${ARCH}"
  bash ${StartSoftwarePath} ${StartSoftware} start ${ServerName} "${Command}"
  WaitingProgressBar
  ScreenSizeMsgbox
  whiptail --title "WebDAV-SM" \
  --msgbox "${ServerName} 启动完成" \
  ${HEIGHT} ${WIDTH}
  ;;
2)
  if StartCheck
  then
    bash ${StartSoftwarePath} ${StartSoftware} stop ${ServerName} > /dev/null 2>&1
  else
    ScreenSizeMsgbox
    whiptail --title "WebDAV-SM" \
    --msgbox "${ServerName} [未启动]" \
    ${HEIGHT} ${WIDTH}
  fi
  ;;
3)
  ScreenSizeMenu
  Number=$(whiptail \
  --title "WebDAV-SM" \
  --menu "WebDAV配置" \
  ${HEIGHT} ${WIDTH} ${OPTION} \
  "1" "🍀 修改用户名" \
  "2" "🌸 修改密码" \
  "3" "🍁 修改路径" \
  "4" "🌷 用户验证" \
  "0" "🍥 返回主菜单" \
  3>&1 1>&2 2>&3)
  case ${Number} in
  1)
    ScreenSizeMsgbox
    username=$(whiptail \
    --title "WebDAV-SM" \
    --inputbox "请输入用户名" \
    ${HEIGHT} ${WIDTH} \
    3>&1 1>&2 2>&3)
    feedback=$?
    if [ ${feedback} == 1 ]
    then
      return
    fi
    sed -i "s/' - username: admin'/  - username: ${username}/g" ${ConfigPath}
    ScreenSizeMsgbox
    whiptail --title "WebDAV-SM" \
    --msgbox "修改完成" \
    ${HEIGHT} ${WIDTH}
    ;;
  2)
    ScreenSizeMsgbox
    password=$(whiptail \
    --title "WebDAV-SM" \
    --passwordbox "请输入密码" \
    ${HEIGHT} ${WIDTH} \
    3>&1 1>&2 2>&3)
    feedback=$?
    if [ ${feedback} == 1 ]
    then
      return
    fi
    sed -i "s/'   password: admin'/    password: ${password}/g" ${ConfigPath}
    ScreenSizeMsgbox
    whiptail --title "WebDAV-SM" \
    --msgbox "修改完成" \
    ${HEIGHT} ${WIDTH}
    ;;
  3)
    ScreenSizeMsgbox
    scope=$(whiptail \
    --title "WebDAV-SM" \
    --inputbox "请输入路径" \
    ${HEIGHT} ${WIDTH} \
    3>&1 1>&2 2>&3)
    feedback=$?
    if [ ${feedback} == 1 ]
    then
      return
    fi
    echo sed -i "s|$(grep scope ${ConfigPath})|    scope: ${scope}|g" ${ConfigPath}
    sed -i "s|$(grep scope ${ConfigPath})|    scope: ${scope}|g" ${ConfigPath}
    ;;
  4)
    ScreenSizeMsgbox
    if $(whiptail --title "WebDAV-SM" \
    --yes-button "开启" \
    --no-button "关闭" \
    --yesno "是否开启或关闭用户验证?" \
    ${HEIGHT} ${WIDTH})
    if [ ${feedback} == 1 ]
    then
      return
    fi
    then
      sed -i "s/$(grep auth)/'auth: true'/g" ${ConfigPath}
    else
      sed -i "s/$(grep auth)/'auth: false'/g" ${ConfigPath}
    fi
    ScreenSizeMsgbox
    whiptail --title "WebDAV-SM" \
    --msgbox "修改完成" \
    ${HEIGHT} ${WIDTH}
    ;;
  0)
    WebDAVMENU
    ;;
  esac
  ;;
  0)
    return 3
  ;;
esac
}

function LoopWebDAVMENU(){
while true
do
  WebDAVMENU
  feedback=$?
  if [ ${feedback} == 3 ]
  then
    exit
  fi
  LoopWebDAVMENU
done
}
LoopWebDAVMENU