#!/bin/env bash
JREInstall(){
ScreenSizeMenu
Number=$(dialog \
--title "创建服务器" \
--menu "您想要使用哪个Java版本？" \
${HEIGHT} ${WIDTH} ${OPTION} \
"1" "🍑 JRE-Java21" \
"2" "🥑 JRE-Java20" \
"3" "🥒 JRE-Java19" \
"4" "🥝 JRE-Java18" \
"5" "🍍 JRE-Java17" \
"6" "🍎 JRE-Java11" \
"7" "🫐 JRE-Java8" \
"0" "返回脚本主菜单" \
3>&1 1>&2 2>&3)
case ${Number} in
1)
  JavaVersion="21"
  ;;
2)
  JavaVersion="20"
  ;;
3)
  JavaVersion="19"
  ;;
4)
  JavaVersion="18"
  ;;
5)
  JavaVersion="17"
  ;;
6)
  JavaVersion="11"
  ;;
7)
  JavaVersion="8"
  ;;
esac
echo ${JavaVersion} >> version
if [ -e $BHHOME/Server/JRE${JavaVersion} ]
then
  ScreenSizeMsgbox
  dialog --title "白狐-Script" \
  --msgbox "您的已安装JRE${JavaVersion} \n无需重复安装" \
  ${HEIGHT} ${WIDTH}
  exit 3
fi
ScreenSizeMsgbox
if $(dialog --title "MCServer-JRE" \
--yes-button "Temurin清华源" \
--no-button "Temurin官方源" \
--yesno "请选择您的JRE下载源" \
${HEIGHT} ${WIDTH})
then
  URL="https://mirrors.tuna.tsinghua.edu.cn/Adoptium"
  JREJavaURL=${URL}/${JavaVersion}/jre/${ARCH}/linux/
  echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息...${background}
  FileName=$(curl ${JREJavaURL} | grep -oP 'href=\K[^ ]+' | tail -n 1 | sed 's/"//g')
  JREDownloadURL=${JREJavaURL}${FileName}
else
  URL="https://ipinfo.io"
  Address=$(curl -sL ${URL} | sed -n 's/.*"country": "\(.*\)",.*/\1/p')
  if [ "${Address}" = "CN" ]
  then
    # 免费提供 请勿滥用
    GitMirror="https://ghproxy.arcticfox.top/"
  fi
  URL="${GitMirror}https://github.com/adoptium/temurin${JavaVersion}-binaries/releases"
  echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息...${background}
  JREJavaVersion=$(curl ${URL} | grep '</h2>' | grep jdk | sed '1s/.*>\(.*\)<.*/\1/p' | head -n 1)
  Version=$(echo ${JREJavaVersion} | sed 's/jdk-//g' | sed 's/+/_/g')
  JREDownloadURL=${URL}/download/${JREJavaVersion}/OpenJDK${JavaVersion}U-debugimage_${ARCH}_linux_hotspot_${Version}.tar.gz
fi
Download JRE.tar.gz ${JREDownloadURL}
if [ -e $BHHOME/Server/JRE${JavaVersion} ]
then
  ScreenSizeMsgbox
  dialog --title "白狐-Script" \
  --msgbox "您的已安装JRE${JavaVersion} \n无需重复安装" \
  ${HEIGHT} ${WIDTH}
  exit 3
else
  cd $BHHOME/Server
  mkdir JRE${JavaVersion}
  echo -e ${blue}[${green}*${blue}] ${cyan}正在解压 ${yellow}JRE${JavaVersion}...${background}
  pv JRE.tar.gz | tar -zxf - -C JRE${JavaVersion}
  JavaFolder=$(ls JRE${JavaVersion})
  mv JRE${JavaVersion}/${JavaFolder}/* JRE
  rm -rf JRE${JavaVersion}/${JavaFolder}
  echo -e ${blue}[${green}*${blue}] ${cyan}解压完成.${background}
fi
}

ARCH=$(uname -m)
case "$ARCH" in
  aarch64|arm64|armv8|armv9)
    ARCH="aarch64"
    JREInstall
    ;;
  arm*|aarch32)
    ScreenSizeMsgbox
    dialog --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n无法运行JRE64" \
    ${HEIGHT} ${WIDTH}
    exit 3
    ;;
  x86_64|x64|amd64)
    ARCH="x64"
    JREInstall
    ;;
  i386|i686|x86)  
    ScreenSizeMsgbox
    dialog --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n无法运行JRE64" \
    ${HEIGHT} ${WIDTH}
    exit 3
    ;;
  *)
    ScreenSizeMsgbox
    dialog --title "白狐-Script" \
    --msgbox "十分抱歉 您的架构为${ARCH} \n属于未知架构" \
    ${HEIGHT} ${WIDTH}
    exit 3
    ;;
esac



