#!/bin/env bash
ReturnValue(){
res=$?
if [ ${res} == 0 ]
then
  exit 0
else
  exit 1
fi
}
case $1 in
tmux)
  case $2 in
    start)
        tmux new -s $3 -d "$4"
        ReturnValue
      ;;
    stop)
        tmux kill-session -t $3 
        ReturnValue
      ;;
    restart)
        tmux kill-session -t $3
        ReturnValue
        tmux new -s $3 -d "$4"
        ReturnValue
      ;;
    log)
        tmux attach -t $3 > /dev/null 2>&1
        ReturnValue
      ;;
    list)
        tmux ls
        ReturnValue
      ;;
    esac
  ;;
screen)
  case $2 in
    start)
      screen -S $3 -d -m bash -c "$4"
      ;;
    stop)
      Session=$(screen -ls | grep $3 | awk '{print $1}')
      screen -X -S ${Session} quit
      ;;
    restart)
      Session=$(screen -ls | grep $3 | awk '{print $1}')
      screen -X -S ${Session} quit
      ReturnValue
      screen -S ${Session} -d -m bash -c "$4"
      ReturnValue
      ;;
    log)
      Session=$(screen -ls | grep $3 | awk '{print $1}')
      screen -r ${Session}
      ReturnValue
      ;;
    list)
      screen -ls
      ;;
  esac
  ;;
esac