#!/bin/env bash
WEBURLNew="https://repo.spongepowered.org/service/rest/repository/browse/maven-releases/org/spongepowered/spongevanilla/"

WEBURLOld="https://repo.spongepowered.org/service/rest/repository/browse/legacy-transfer/org/spongepowered/spongevanilla/"

if $(whiptail --title "MCServer-BDS" \
--yes-button "稳定版" \
--no-button "测试版" \
--yesno "请选择您的版本" \
${HEIGHT} ${WIDTH} \
3>&1 1>&2 2>&3)
then
    GREPURL=${WEBURLNew}
else
    GREPURL=${WEBURLOld}
fi
echo -e ${blue}[${green}*${blue}] ${cyan}正在获取 ${yellow}版本信息${background}

curl https://repo.spongepowered.org/service/rest/repository/browse/maven-releases/org/spongepowered/spongevanilla/ | grep -E href=\".*'RC'.*\"\> | sed 's|</a></td>||g' | sed 's|<td><a href="||g' | sed "s|/\">.*||" | sed "s| ||g" 